# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :betaTestFlight do
    increment_build_number(xcodeproj: "ios/rnFastlaneTest1App.xcodeproj")
    match(type: "appstore")
    gym(workspace: "ios/rnFastlaneTest1App.xcworkspace", scheme: "rnFastlaneTest1App")
    upload_to_testflight
  end
end

#platform :ios do
#  desc "Push a new beta build to TestFlight"
#  lane :beta do
#    increment_build_number(xcodeproj: "itauSelphiTest5App.xcodeproj")
#    build_app(workspace: "itauSelphiTest5App.xcworkspace", scheme: "itauSelphiTest5App")
#    upload_to_testflight
#  end
#end

